spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/security_db?allowPublicKeyRetrieval=true&useSSL=false
    username: security_user
    password: security_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        ues_sql_comment: true
        default_batch_fetch_size: 1000
    open-in-view: true

  security:
    user:
      name: user1
      password: 1234
      roles: USER

server:
  port: 9000

logging:
  level:
    root: info
    org.hibernate.SQL: debug

